# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

admin = User.new( nome: 'Administrador', email: 'admin@localhost', password: 'admin', admin: true ).save(validate: false)

tipos = Tipo.create([
 { nome: "Bateria Recarregavel"},
 { nome: "Caixa de som"},
 { nome: "Câmera"},
 { nome: "Câmera Digital"},
 { nome: "Câmera HD"},
 { nome: "Câmera Profissional"},
 { nome: "Interface de Audio"},
 { nome: "Mesa de som"},
 { nome: "Microfone Package"},
 { nome: "Microfone sem fio"},
 { nome: "Notebook"},
 { nome: "Retroprojetor"},
 { nome: "Tripé"},
 { nome: "WebCam" }
])

modelos = Modelo.create([
 { nome: "8922"},
 { nome: "Coolpix P520"},
 { nome: "CSR2500A/USB"},
 { nome: "Cyber-Shot DSC-W510"},
 { nome: "DS126281"},
 { nome: "Fast Track Pro"},
 { nome: "GR-AX26U"},
 { nome: "GY-DV300U"},
 { nome: "H434A"},
 { nome: "HDR-XR550V"},
 { nome: "HT00"},
 { nome: "HXR-NX70U"},
 { nome: "LifeCam BX-7000"},
 { nome: "Não tem"},
 { nome: "NP405G"},
 { nome: "NP-FV100"},
 { nome: "ProBook 6465b"},
 { nome: "Sem modelo"},
 { nome: "UHF 271"},
 { nome: "UWP-D16"},
 { nome: "VPL-ES4"},
 { nome: "XENYX 1622FX"}
])

marcas = Marca.create([
 { nome: "BEHRINGER"},
 { nome: "Canon"},
 { nome: "CSR"},
 { nome: "EPSON"},
 { nome: "HP"},
 { nome: "JVC"},
 { nome: "Lenovo"},
 { nome: "M-AUDIO"},
 { nome: "Microsoft"},
 { nome: "Multilaser"},
 { nome: "Não tem"},
 { nome: "NEC"},
 { nome: "Nikon"},
 { nome: "SKP Pro Audio"},
 { nome: "SONY"}
])

equipamentos = Equipamento.create([
  { tipo_id: Tipo.where(nome: "Microfone sem fio").first.id,
    marca_id: Marca.where(nome: "SKP Pro Audio").first.id,
    modelo_id: Modelo.where(nome: "UHF 271").first.id,
    patrimonio: "374467",
    numero_serie: "0",
    local_retirada: :LICOSC },
  { tipo_id: Tipo.where(nome: "Microfone sem fio").first.id,
    marca_id: Marca.where(nome: "SKP Pro Audio").first.id,
    modelo_id: Modelo.where(nome: "UHF 271").first.id,
    patrimonio: "374468",
    numero_serie: "0",
    local_retirada: :LICOSC },
  { tipo_id: Tipo.where(nome: "Microfone sem fio").first.id,
    marca_id: Marca.where(nome: "SKP Pro Audio").first.id,
    modelo_id: Modelo.where(nome: "UHF 271").first.id,
    patrimonio: "374470",
    numero_serie: "0",
    local_retirada: :LICOSC },
  { tipo_id: Tipo.where(nome: "Microfone sem fio").first.id,
    marca_id: Marca.where(nome: "SKP Pro Audio").first.id,
    modelo_id: Modelo.where(nome: "UHF 271").first.id,
    patrimonio: "374471",
    numero_serie: "0",
    local_retirada: :LICOSC },
  { tipo_id: Tipo.where(nome: "Mesa de som").first.id,
    marca_id: Marca.where(nome: "BEHRINGER").first.id,
    modelo_id: Modelo.where(nome: "XENYX 1622FX").first.id,
    patrimonio: "328613",
    numero_serie: "0",
    local_retirada: :LICOSC },
  { tipo_id: Tipo.where(nome: "Mesa de som").first.id,
    marca_id: Marca.where(nome: "BEHRINGER").first.id,
    modelo_id: Modelo.where(nome: "XENYX 1622FX").first.id,
    patrimonio: "328614",
    numero_serie: "0",
    local_retirada: :LICOSC },
  { tipo_id: Tipo.where(nome: "Caixa de som").first.id,
    marca_id: Marca.where(nome: "CSR").first.id,
    modelo_id: Modelo.where(nome: "CSR2500A/USB").first.id,
    patrimonio: "334839",
    numero_serie: "0",
    local_retirada: :LICOSC },
  { tipo_id: Tipo.where(nome: "Caixa de som").first.id,
    marca_id: Marca.where(nome: "CSR").first.id,
    modelo_id: Modelo.where(nome: "CSR2500A/USB").first.id,
    patrimonio: "334840",
    numero_serie: "0",
    local_retirada: :LICOSC },
  { tipo_id: Tipo.where(nome: "Retroprojetor").first.id,
    marca_id: Marca.where(nome: "EPSON").first.id,
    modelo_id: Modelo.where(nome: "H434A").first.id,
    patrimonio: "361145",
    numero_serie: "0",
    local_retirada: :LICOSC },
  { tipo_id: Tipo.where(nome: "Retroprojetor").first.id,
    marca_id: Marca.where(nome: "EPSON").first.id,
    modelo_id: Modelo.where(nome: "H434A").first.id,
    patrimonio: "361146",
    numero_serie: "0",
    local_retirada: :LICOSC },
  { tipo_id: Tipo.where(nome: "Retroprojetor").first.id,
    marca_id: Marca.where(nome: "EPSON").first.id,
    modelo_id: Modelo.where(nome: "H434A").first.id,
    patrimonio: "361147",
    numero_serie: "0",
    local_retirada: :LICOSC },
  { tipo_id: Tipo.where(nome: "Retroprojetor").first.id,
    marca_id: Marca.where(nome: "NEC").first.id,
    modelo_id: Modelo.where(nome: "NP405G").first.id,
    patrimonio: "324634",
    numero_serie: "0",
    local_retirada: :LICOSC },
  { tipo_id: Tipo.where(nome: "Retroprojetor").first.id,
    marca_id: Marca.where(nome: "SONY").first.id,
    modelo_id: Modelo.where(nome: "VPL-ES4").first.id,
    patrimonio: "267673",
    numero_serie: "0",
    local_retirada: :LICOSC },
  { tipo_id: Tipo.where(nome: "WebCam").first.id,
    marca_id: Marca.where(nome: "Microsoft").first.id,
    modelo_id: Modelo.where(nome: "Sem modelo").first.id,
    patrimonio: "334650",
    numero_serie: "0",
    local_retirada: :LICOSC },
  { tipo_id: Tipo.where(nome: "Notebook").first.id,
    marca_id: Marca.where(nome: "HP").first.id,
    modelo_id: Modelo.where(nome: "ProBook 6465b").first.id,
    patrimonio: "369554",
    numero_serie: "0",
    local_retirada: :LICOSC },
  { tipo_id: Tipo.where(nome: "Notebook").first.id,
    marca_id: Marca.where(nome: "Lenovo").first.id,
    modelo_id: Modelo.where(nome: "8922").first.id,
    patrimonio: "Não tem",
    numero_serie: "0",
    local_retirada: :LICOSC },
  { tipo_id: Tipo.where(nome: "Notebook").first.id,
    marca_id: Marca.where(nome: "Não tem").first.id,
    modelo_id: Modelo.where(nome: "HT00").first.id,
    patrimonio: "328365",
    numero_serie: "0",
    local_retirada: :LICOSC },
  { tipo_id: Tipo.where(nome: "Caixa de som").first.id,
    marca_id: Marca.where(nome: "Multilaser").first.id,
    modelo_id: Modelo.where(nome: "Não tem").first.id,
    patrimonio: "Não tem",
    numero_serie: "0",
    local_retirada: :LICOSC },
  { tipo_id: Tipo.where(nome: "Câmera").first.id,
    marca_id: Marca.where(nome: "Nikon").first.id,
    modelo_id: Modelo.where(nome: "Coolpix P520").first.id,
    patrimonio: "Não tem",
    numero_serie: "0",
    local_retirada: :LICOSC },
  { tipo_id: Tipo.where(nome: "Câmera").first.id,
    marca_id: Marca.where(nome: "Nikon").first.id,
    modelo_id: Modelo.where(nome: "Coolpix P520").first.id,
    patrimonio: "Não tem",
    numero_serie: "0",
    local_retirada: :LICOSC },
  { tipo_id: Tipo.where(nome: "Câmera").first.id,
    marca_id: Marca.where(nome: "JVC").first.id,
    modelo_id: Modelo.where(nome: "GR-AX26U").first.id,
    patrimonio: "Não tem",
    numero_serie: "0",
    local_retirada: :LICOSC },
  { tipo_id: Tipo.where(nome: "Câmera Digital").first.id,
    marca_id: Marca.where(nome: "SONY").first.id,
    modelo_id: Modelo.where(nome: "Cyber-Shot DSC-W510").first.id,
    patrimonio: "374461",
    numero_serie: "0",
    local_retirada: :LICOSC },
  { tipo_id: Tipo.where(nome: "Câmera").first.id,
    marca_id: Marca.where(nome: "Canon").first.id,
    modelo_id: Modelo.where(nome: "DS126281").first.id,
    patrimonio: "Não tem",
    numero_serie: "0",
    local_retirada: :LICOSC },
  { tipo_id: Tipo.where(nome: "Câmera Profissional").first.id,
    marca_id: Marca.where(nome: "JVC").first.id,
    modelo_id: Modelo.where(nome: "GY-DV300U").first.id,
    patrimonio: "213667",
    numero_serie: "0",
    local_retirada: :LICOSC },
  { tipo_id: Tipo.where(nome: "Câmera HD").first.id,
    marca_id: Marca.where(nome: "SONY").first.id,
    modelo_id: Modelo.where(nome: "HXR-NX70U").first.id,
    patrimonio: "Não tem",
    numero_serie: "0",
    local_retirada: :LICOSC },
  { tipo_id: Tipo.where(nome: "Câmera HD").first.id,
    marca_id: Marca.where(nome: "SONY").first.id,
    modelo_id: Modelo.where(nome: "HXR-NX70U").first.id,
    patrimonio: "Não tem",
    numero_serie: "0",
    local_retirada: :LICOSC },
  { tipo_id: Tipo.where(nome: "Câmera HD").first.id,
    marca_id: Marca.where(nome: "SONY").first.id,
    modelo_id: Modelo.where(nome: "HXR-NX70U").first.id,
    patrimonio: "Não tem",
    numero_serie: "0",
    local_retirada: :LICOSC },
  { tipo_id: Tipo.where(nome: "Câmera HD").first.id,
    marca_id: Marca.where(nome: "SONY").first.id,
    modelo_id: Modelo.where(nome: "HDR-XR550V").first.id,
    patrimonio: "353460",
    numero_serie: "0",
    local_retirada: :LICOSC },
  { tipo_id: Tipo.where(nome: "Câmera HD").first.id,
    marca_id: Marca.where(nome: "SONY").first.id,
    modelo_id: Modelo.where(nome: "HDR-XR550V").first.id,
    patrimonio: "353461",
    numero_serie: "0",
    local_retirada: :LICOSC },
  { tipo_id: Tipo.where(nome: "Bateria Recarregavel").first.id,
    marca_id: Marca.where(nome: "SONY").first.id,
    modelo_id: Modelo.where(nome: "NP-FV100").first.id,
    patrimonio: "Não tem",
    numero_serie: "0",
    local_retirada: :LICOSC },
  { tipo_id: Tipo.where(nome: "Interface de Audio").first.id,
    marca_id: Marca.where(nome: "M-AUDIO").first.id,
    modelo_id: Modelo.where(nome: "Fast Track Pro").first.id,
    patrimonio: "331872",
    numero_serie: "0",
    local_retirada: :LICOSC },
  { tipo_id: Tipo.where(nome: "Microfone Package").first.id,
    marca_id: Marca.where(nome: "SONY").first.id,
    modelo_id: Modelo.where(nome: "UWP-D16").first.id,
    patrimonio: "Não tem",
    numero_serie: "0",
    local_retirada: :LICOSC },
  { tipo_id: Tipo.where(nome: "WebCam").first.id,
    marca_id: Marca.where(nome: "Microsoft").first.id,
    modelo_id: Modelo.where(nome: "LifeCam BX-7000").first.id,
    patrimonio: "334661",
    numero_serie: "0",
    local_retirada: :LICOSC },
  { tipo_id: Tipo.where(nome: "Tripé").first.id,
    marca_id: Marca.where(nome: "Não tem").first.id,
    modelo_id: Modelo.where(nome: "Não tem").first.id,
    patrimonio: "239620",
    numero_serie: "0",
    local_retirada: :LICOSC },
  { tipo_id: Tipo.where(nome: "Tripé").first.id,
    marca_id: Marca.where(nome: "Não tem").first.id,
    modelo_id: Modelo.where(nome: "Não tem").first.id,
    patrimonio: "239621",
    numero_serie: "0",
    local_retirada: :LICOSC },
  { tipo_id: Tipo.where(nome: "Tripé").first.id,
    marca_id: Marca.where(nome: "Não tem").first.id,
    modelo_id: Modelo.where(nome: "Não tem").first.id,
    patrimonio: "381735",
    numero_serie: "0",
    local_retirada: :LICOSC },
  { tipo_id: Tipo.where(nome: "Tripé").first.id,
    marca_id: Marca.where(nome: "Não tem").first.id,
    modelo_id: Modelo.where(nome: "Não tem").first.id,
    patrimonio: "Não tem",
    numero_serie: "0",
    local_retirada: :LICOSC },
  { tipo_id: Tipo.where(nome: "Tripé").first.id,
    marca_id: Marca.where(nome: "Não tem").first.id,
    modelo_id: Modelo.where(nome: "Não tem").first.id,
    patrimonio: "Não tem",
    numero_serie: "0",
    local_retirada: :LICOSC },
])

